server:
  port: 8517
spring:
  application:
    name: xbin-store-cloud-service-cart
  datasource:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.jdbc.Driver
          platform: mysql
          url: jdbc:mysql://154.8.147.101:3306/shop_demo?characterEncoding=utf-8
          username: guest
          password: mysql@2018!
          hikari:
             connectionTimeout: 30000
             idleTimeout: 600000
             maximumPoolSize: 60
             minimumIdle: 10
  redis:
    host: 127.0.0.1
    password:
    port: 6379

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

##mybatis
mybatis:
    type-aliases-package: cn.binux.pojo
    mapper-locations: classpath:mapper/*.xml

##eureka conf
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.xbin.store.com:8501/eureka/

##swagger2 conf
swagger2:
  package: cn.binux.cart.service

##pageHelper conf
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    # 购物车
    cart_info_profix: 'CART_INFO:'
    # 商品
    item_info_profix: 'ITEM_INFO:'
    item_info_base_suffix: ':BASE'
    item_info_desc_suffix: ':DESC'
    # Redis 缓存时间 默认3天
    redis_cart_expire_time: 259200
  
