#配置模板想到classpath路径，后面须加上"/"
beetl:
  templates-path: templates/
  config:
      html-tag-flag: true
#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html
  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${resource.static.path}
    static-locations: file:${resource.static.path}

# swagger2
swagger2.package: cn.binux.controller

redis:
  cluster: false
  single-host: ${redis.host}
  single-port: ${redis.port}
  password: ${redis.password}

# Redis
redisKey:
  # 订单项缓存时间 默认20分钟
  expire_time: 1200
  prefix:
    # Redis购物车商品信息前缀
    cart_order_info_profix: 'CART_ORDER_INFO:'
    # Redis购物车索引信息前缀
    cart_order_index_profix: 'CART_ORDER_INDEX:'
    # 用户登录信息前缀
    user_session: 'USER_SESSION:'
    # 验证码Redis前缀
    verifycode: 'VERIFYCODE:'


#系统登录页面
#user_login_page: 'http://192.168.100.222:8101/login.html'
user_login_page: '/login'
# 密码错误
password_error: '({"pwd":"\u8d26\u6237\u540d\u4e0e\u5bc6\u7801\u4e0d\u5339\u914d\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165\","_t":"_ntInoTX"})'
# 用户名不存在
user_not_exist: '({"pwd":"\u8d26\u6237\u540d\u4e0e\u5bc6\u7801\u4e0d\u5339\u914d\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165<br/>\u5982\u9700\u6d77\u5916\u624b\u673a\u767b\u5f55\u8bf7\u6dfb\u52a0 <a href=\\"javascript:void(0);" id="country_code_selector" class="flk13" style="color:blue;">\u56fd\u5bb6\u533a\u53f7</a>","_t":"_ntqtNMt","countryTips":true})'
# 成功响应首页
homepage_path: '({"success":"http://192.168.100.222:8101/"})'

# 广告Cid
big_ad_index: 1


## Search Rows
search_result_rows: 60
