server:
  port: 8515
spring:
  application:
    name: xbin-store-cloud-service-user
  datasource:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.jdbc.Driver
          platform: mysql
          url: jdbc:mysql://154.8.147.101:3306/shop_demo?characterEncoding=utf-8
          username: guest
          password: mysql@2018!
          hikari:
             connectionTimeout: 30000
             idleTimeout: 600000
             maximumPoolSize: 60
             minimumIdle: 10
  redis:
    host: 127.0.0.1
    password:
    port: 6379

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

##mybatis
mybatis:
    type-aliases-package: cn.binux.pojo
    mapper-locations: classpath:mapper/*.xml

##eureka conf
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.xbin.store.com:8501/eureka/

##swagger2 conf
swagger2:
  package: cn.binux.user.service

##pageHelper conf
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    # 用户登录信息前缀
    user_session: 'USER_SESSION:'
    # 验证码Redis前缀
    verifycode: 'VERIFYCODE:'
    # 号码code
    mobile_login_code: 'MOBILE_LOGIN_CODE:'

login:
  # 验证名
  validation:
    #登录名
    ispinengaged: isPinEngaged
    #邮箱
    isemailengaged: isEmailEngaged
    #手机
    ismobileengaged: isMobileEngaged
  # 推荐登录名后缀随机数取值范围
  random_number: 50000
  # 登录成功页面
  success_url: http://eureka.xbin.store.com:8101/success
